# coding=utf-8
# *** WARNING: this file was generated by Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .gcp_bucket import *
from .provider import *
_utilities.register(
    resource_modules="""
[
 {
  "pkg": "squid",
  "mod": "index",
  "fqn": "pulumi_squid",
  "classes": {
   "squid:index:GCPBucket": "GCPBucket"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "squid",
  "token": "pulumi:providers:squid",
  "fqn": "pulumi_squid",
  "class": "Provider"
 }
]
"""
)
