name: release
on:
  push:
    tags:
      - v*.*.*
      - '!v*.*.*-**'
env:
  PROVIDER: "squid"
  
  GITHUB_TOKEN: ${{ YOUR GITHUB TOKEN HERE }}
  
  NODE_AUTH_TOKEN: ${{ YOUR NPM TOKEN HERE }}
  NPM_TOKEN: ${{ YOUR NPM TOKEN HERE }}
  PUBLISH_NPM: false
  NPM_REGISTRY_URL: https://registry.npmjs.org

  NUGET_PUBLISH_KEY: ${{ YOUR NUGET PUBLISH KEY HERE }}
  NUGET_FEED_URL: https://api.nuget.org/v3/index.json
  PUBLISH_NUGET: false

  PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
  PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
  PYPI_REPOSITORY_URL: ""
  PUBLISH_PYPI: true

jobs:
  publish-binary:
    name: publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Unshallow clone for tags
      run: git fetch --prune --unshallow --tags
